### ISSUE TITLE
Support for iOS8

### ISSUE THREAD

**Issue by shvekiasaf** [nicolaschengdev/WYPopoverController#130]
Do you plan to support iOS 8 soon? 
There is an issue with changing orientations, it doesn't work well.

Thank you.

**Comment by sammcewan** [comment]
I am actively working on fixing this here. Hoping to get it resolved next week.
https://github.com/sammcewan/WYPopoverController/tree/fix-iOS8-orientation-handling

**Comment by shvekiasaf** [comment]
Thanks!

**Comment by sammcewan** [comment]
FYI for anyone viewing this the above PR resolves key issues mainly relating to changes in orientation handling in iOS8. This fixed this library for me. Would love to get this merged but activity on this repo has been dead for months.

**Comment by gpdawson** [comment]
Thanks Sam - this is a really useful control - your work to update it is appreciated by me, at least.

**Comment by vitalys** [comment]
@sammcewan, thanks for your fix, but there is a serious bug. You add observer for `preferredContentSize` value on every call of `presentPopoverFromRect`, but it can be called to move popover, without dismissing. As result you can add observer more than one time and remove it only once in `dismissPopoverAnimated`. Additional flag like `isListeningNotifications` is required to avoid this.

**Comment by sammcewan** [comment]
@vitalys Thanks for raising. Please feel free to get a fix into this iOS8 support branch.

**Comment by vitalys** [comment]
@sammcewan, I've just created a pull request with my fix.

**Comment by pablogeek** [comment]
Please ios8 is comming , I hope to get the library fixed in a few days ;)

**Comment by sammcewan** [comment]
Use the branch in the pull request we've been working on @pablogeek. I doubt we'll see it accepted any time soon.

**Comment by pablogeek** [comment]
I'm using cocoapods, can I use the branch in the pull request on cocoapods?

**Comment by ashavit** [comment]
@pablogeek You can use this line for the podfile:
pod 'WYPopoverController' ,:git => 'https://github.com/sammcewan/WYPopoverController.git', :branch => 'fix-iOS8-orientation-handling'
It takes @sammcewan fix, and it worked for me

**Comment by RayzorDragon** [comment]
I'm still having a problem with production builds on ios 8 beta devices still showing the popups sideways despite using the ios 8 fix branch. This does not happen when building debug builds on either my simulators or on my same ios 8 beta devices. Has anyone else experienced this?

**Comment by pablogeek** [comment]
I have this problem in iOS8

![img_0004](https://cloud.githubusercontent.com/assets/1773546/4187160/567642da-3767-11e4-9921-8e8dbd99fb0f.PNG)

**Comment by sammcewan** [comment]
@pablogeek The popover is behaving correctly I suspect this could be something to do with implicit autolayout constraints. I would start there. If you find a fix please PR to my branch. I will surely accept. I'll have a look if I have time this weekend too.

**Comment by danielwilliamson** [comment]
I am also experiencing a problem where the view cuts off but only in a when selecting a particular cell in the third column. Very weird, the default popover works fine. Any help would be great. Thanks
![screen shot 2014-09-24 at 16 50 17](https://cloud.githubusercontent.com/assets/6487407/4391159/bf218d56-4402-11e4-81e8-a3ee0d6517f8.png)
![screen shot 2014-09-24 at 16 50 24](https://cloud.githubusercontent.com/assets/6487407/4391160/c0f67c68-4402-11e4-9231-bc7c4180059d.png)

**Comment by onmyway133** [comment]
Why not use a version check and use UIPopoverPresentationController for iOS 8 ?

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIPopoverPresentationController_class/index.html
http://stackoverflow.com/questions/25319179/uipopoverpresentationcontroller-on-ios-8-iphone

You can write a wrapper like this FTGPopoverController https://gist.github.com/onmyway133/b62f79b885a71c41a22a

**Comment by airbob** [comment]
thank you so much @sammcewan !
